import axios from 'axios'
import * as fs from 'node:fs'
import * as path from 'node:path'
import FormData from 'form-data'
import type { Server } from 'http'
import { fileURLToPath } from 'node:url'
const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

// This smoke test validates slicing through the node-api service using the
// A1/A1M minimal vendor bundle that orca.ts injects. It asserts a successful
// HTTP response and that the returned payload contains plausible G-code.

describe('slicer: A1 smoke (end-to-end)', function () {
  this.timeout(180_000)

  let server: Server | null = null
  let baseURL = ''
  let appRef: any = null

  before(async () => {
    // Ensure the addon prefers the locally-built engine from the monorepo
    const nodeApiRoot = path.resolve(__dirname, '../../../..')
    const repoRoot = path.resolve(nodeApiRoot, '..')

    process.env.ORCACLI_PREFER_LOCAL = '1'
    process.env.ORCACLI_ENGINE_PATH = path.join(
      repoRoot,
      'OrcaSlicerAddon/build/bindings/node/liborcacli_engine.dylib'
    )

    // Import app after env is set so src/orca.ts picks up the variables
    const mod = await import('../../../src/app')
    appRef = (mod as any).app
    server = await appRef.listen(0)

    const address = server.address()
    const port = typeof address === 'string' || address === null ? 0 : address.port
    baseURL = `http://127.0.0.1:${port}`
  })

  after(async () => {
    try {
      if (appRef?.teardown) await appRef.teardown()
    } catch {}
    try {
      if (server) server.close()
    } catch {}
  })

  it('should slice STL and return valid G-code', async () => {
    const repoRoot = path.resolve(__dirname, '../../../..')
    const stlPath = path.join(repoRoot, 'example_files/3DBenchy.stl')
    if (!fs.existsSync(stlPath)) {
      throw new Error(`Exemplo STL não encontrado em ${stlPath}`)
    }

    const form = new FormData()
    form.append('file', fs.createReadStream(stlPath), {
      filename: '3DBenchy.stl',
      contentType: 'application/sla'
    })

    const resp = await axios.post(`${baseURL}/slicer/stl`, form, {
      headers: form.getHeaders(),
      maxBodyLength: Infinity,
      maxContentLength: Infinity,
      validateStatus: () => true
    })

    if (resp.status !== 201) {
      throw new Error(`Status inesperado: ${resp.status}`)
    }

    const data = resp.data
    if (!(data && typeof data === 'object')) {
      throw new Error('Resposta não é objeto')
    }

    const outputPath: string | undefined = (data as any).outputPath
    const gcode: string | undefined = (data as any).gcode

    if (!outputPath || !fs.existsSync(outputPath)) {
      throw new Error(`Arquivo de saída inexistente em disco: ${outputPath}`)
    }

    if (!gcode || gcode.length < 50) {
      throw new Error('G-code ausente ou muito curto')
    }

    const hasCommands = /(\n|^)G\d+|M\d+/.test(gcode)
    const hasHeaderMark = gcode.includes(';') || /; generated by/i.test(gcode)
    if (!(hasCommands || hasHeaderMark)) {
      throw new Error('Conteúdo não parece G-code')
    }
  })
})
