import axios from 'axios'
import * as fs from 'node:fs'
import * as path from 'node:path'
import FormData from 'form-data'
import type { Server } from 'http'
import assert from 'assert'

// Port of the legacy slice_compare logic into a Mocha test that goes through
// the node-api HTTP surface and the strict A1/A1M vendor bundle (see src/orca.ts).
// It compares HEADER_BLOCK, CONFIG_BLOCK and the G-code body with minimal
// normalizations to keep determinism (ignore timestamp and volatile object ids).

describe('slicer: A1 slice comparison vs reference (end-to-end)', function () {
  this.timeout(300_000)

  let server: Server | null = null
  let baseURL = ''
  let appRef: any = null

  const repoRoot = path.resolve(__dirname, '../../../..')
  const stlPath = path.join(repoRoot, 'example_files/3DBenchy.stl')
  const outDir = path.join(repoRoot, 'output_files')
  const outTarget = path.join(outDir, 'node_api_3DBenchy_compare.gcode')

  before(async () => {
    // Ensure output directory exists
    fs.mkdirSync(outDir, { recursive: true })

    // Import app after test/setup.ts configured env (ORCACLI_ENGINE_PATH, etc.)
    const mod = await import('../../../src/app')
    appRef = (mod as any).app
    server = await appRef.listen(0)
    const address = server.address()
    const port = typeof address === 'string' || address === null ? 0 : address.port
    baseURL = `http://127.0.0.1:${port}`
  })

  after(async () => {
    try { if (appRef?.teardown) await appRef.teardown() } catch {}
    try { if (server) server.close() } catch {}
  })

  function extractHeaderBlock(s: string): string {
    const start = s.indexOf('; HEADER_BLOCK_START')
    const end = s.indexOf('; HEADER_BLOCK_END')
    if (start === -1 || end === -1) return ''
    const segment = s.slice(start, end + '; HEADER_BLOCK_END'.length)
    return segment
      .split(/\r?\n/)
      .filter(line => !/^; generated by /.test(line)) // ignore timestamp line
      .join('\n')
  }

  function extractConfigBlock(s: string): string {
    const start = s.indexOf('; CONFIG_BLOCK_START')
    const end = s.indexOf('; CONFIG_BLOCK_END')
    if (start === -1 || end === -1) return ''
    return s.slice(start, end + '; CONFIG_BLOCK_END'.length)
  }

  function extractGcodeCommands(s: string): string {
    const endMark = '; CONFIG_BLOCK_END'
    const idx = s.indexOf(endMark)
    if (idx === -1) return ''
    // Skip the endMark line itself and the next line (tail -n +2 in bash version)
    const after = s.slice(idx + endMark.length)
    const lines = after.split(/\r?\n/)
    const body = lines.slice(1).join('\n')
    return normalizePrintingObjectIds(body)
  }

  function normalizePrintingObjectIds(s: string): string {
    // Make comparison robust against volatile numeric ids in comments
    const lines = s.split(/\r?\n/)
    return lines
      .map(line => {
        if (/^; (printing|stop printing) object .* id:\d+ copy /.test(line)) {
          return line.replace(/id:\d+/, 'id:IGNORED')
        }
        if (/^; (start|stop) printing object, unique label id: \d+$/.test(line)) {
          return line.replace(/id: \d+$/, 'id: IGNORED')
        }
        return line
      })
      .join('\n')
  }

  function firstDiffLine(a: string, b: string): number | null {
    const aLines = a.split(/\r?\n/)
    const bLines = b.split(/\r?\n/)
    const max = Math.max(aLines.length, bLines.length)
    for (let i = 0; i < max; i++) {
      if (aLines[i] !== bLines[i]) return i + 1 // 1-based
    }
    return null
  }

  it('valida A1 end-to-end e invariantes de HEADER/CONFIG', async () => {
    assert.ok(fs.existsSync(stlPath), `STL não encontrado: ${stlPath}`)

    // Prepare multipart form
    const form = new FormData()
    form.append('file', fs.createReadStream(stlPath), {
      filename: '3DBenchy.stl',
      contentType: 'application/sla'
    })
    form.append('output', outTarget)

    // Explicit A1 presets (como no bundle mínimo em src/orca.ts)
    form.append('printerProfile', 'Bambu Lab A1 0.4 nozzle')
    form.append('filamentProfile', 'Generic PLA @BBL A1')
    form.append('processProfile', '0.20mm Standard @BBL A1')

    const resp = await axios.post(`${baseURL}/slicer/stl`, form, {
      headers: form.getHeaders(),
      maxBodyLength: Infinity,
      maxContentLength: Infinity,
      validateStatus: () => true
    })

    assert.strictEqual(resp.status, 201, `Status inesperado: ${resp.status} - ${JSON.stringify(resp.data)}`)

    const outGcode: string = resp.data?.gcode
    assert.ok(typeof outGcode === 'string' && outGcode.length > 1000, 'G-code gerado muito curto')

    // 1) HEADER_BLOCK invariantes (ignorando campos voláteis)
    const outHeader = extractHeaderBlock(outGcode)
    assert.ok(outHeader.includes('; HEADER_BLOCK_START'), 'HEADER_BLOCK_START ausente')
    assert.ok(outHeader.includes('; HEADER_BLOCK_END'), 'HEADER_BLOCK_END ausente')
    assert.ok(/; total layer number: 240/.test(outHeader), 'Total de camadas diferente do esperado (240)')
    assert.ok(/; filament_diameter: 1\.75/.test(outHeader), 'Diâmetro do filamento diferente do esperado (1.75)')
    assert.ok(/; max_z_height: 48\.00/.test(outHeader), 'Altura Z máxima diferente do esperado (48.00)')

    // 2) CONFIG_BLOCK invariantes: perfis padrão devem refletir a seleção A1
    const outCfg = extractConfigBlock(outGcode)
    assert.ok(outCfg.includes('; CONFIG_BLOCK_START') && outCfg.includes('; CONFIG_BLOCK_END'), 'CONFIG_BLOCK markers ausentes')
    assert.ok(/; default_print_profile = 0\.20mm Standard @BBL A1/.test(outCfg), 'default_print_profile não é A1 0.20mm Standard')
    assert.ok(/; default_filament_profile = "Bambu PLA Basic @BBL A1"/.test(outCfg), 'default_filament_profile não é Bambu PLA Basic @BBL A1')

    // 3) Corpo do G-code: deve ter volume significativo e blocos pós-CONFIG
    const body = extractGcodeCommands(outGcode)
    assert.ok(body.length > 100_000, 'G-code (corpo) muito curto para o Benchy A1')
  })
})

