// For more information about this file see https://dove.feathersjs.com/guides/cli/service.test.html
// CommonJS style requires to keep mocha in CJS mode (tsx/register cuida do ESM)
// eslint-disable-next-line @typescript-eslint/no-var-requires
const assert = require('assert') as typeof import('assert')
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { app } = require('../../../../src/app') as { app: any }
// eslint-disable-next-line @typescript-eslint/no-var-requires
const axios = require('axios') as typeof import('axios')
// eslint-disable-next-line @typescript-eslint/no-var-requires
const fs = require('node:fs') as typeof import('node:fs')
// eslint-disable-next-line @typescript-eslint/no-var-requires
const path = require('node:path') as typeof import('node:path')
// eslint-disable-next-line @typescript-eslint/no-var-requires
const FormData = require('form-data') as typeof import('form-data')

describe('slicer/stl service', () => {
  let server: any
  let baseURL: string

  before(async () => {
    server = await app.listen(0)
    const address = server.address()
    const port = typeof address === 'string' || address === null ? 0 : address.port
    baseURL = `http://127.0.0.1:${port}`
  })

  after(async () => {
    await app.teardown()
  })

  it('registered the service', () => {
    const service = app.service('slicer/stl')
    assert.ok(service, 'Registered the service')
  })

  it('faz upload de um STL via multipart e retorna G-code válido', async function () {
    this.timeout(180000) // slicing pode levar dezenas de segundos

    const stlPath = path.resolve(__dirname, '../../../../../example_files/3DBenchy.stl')
    assert.ok(fs.existsSync(stlPath), 'Arquivo de exemplo 3DBenchy.stl não encontrado')

    const form = new FormData()
    form.append('file', fs.createReadStream(stlPath), {
      filename: '3DBenchy.stl',
      contentType: 'application/sla'
    })

    // Salvar em output_files seguindo o template existente, prefixando com "node_api"
    const outDir = path.resolve(__dirname, '../../../../../output_files')
    fs.mkdirSync(outDir, { recursive: true })
    const modelBase = path.basename(stlPath, path.extname(stlPath)) // e.g., '3DBenchy'
    const plate = 1
    const outTarget = path.join(outDir, `node_api_${modelBase}_plate_${plate}.gcode`)
    form.append('output', outTarget)

    // Perfis explícitos para a impressão (usar nomes existentes no engine)
    form.append('printerProfile', 'Bambu Lab X1 Carbon 0.4 nozzle')
    form.append('filamentProfile', 'Bambu PLA Basic @BBL X1C')
    form.append('processProfile', '0.20mm Standard @BBL X1C')

    const resp = await axios.post(`${baseURL}/slicer/stl`, form, {
      headers: form.getHeaders(),
      maxBodyLength: Infinity,
      maxContentLength: Infinity,
      validateStatus: () => true
    })

    assert.strictEqual(resp.status, 201, `Status inesperado: ${resp.status} - ${JSON.stringify(resp.data)}`)
    const data = resp.data

    assert.ok(typeof data === 'object' && data, 'Resposta não é objeto')
    assert.ok(typeof data.outputPath === 'string' && data.outputPath.length > 0, 'outputPath ausente')
    assert.ok(typeof data.gcode === 'string' && data.gcode.length > 50, 'gcode ausente ou muito curto')

    const gcode = data.gcode as string
    const hasCommands = /(\n|^)G\d+|M\d+/.test(gcode)
    const hasHeaderMark = gcode.includes(';') || /; generated by/i.test(gcode)
    assert.ok(hasCommands || hasHeaderMark, 'Conteúdo não parece G-code')

    assert.ok(fs.existsSync(data.outputPath), 'Arquivo de saída não existe no disco')
  })
})
