; HEADER_BLOCK_START
; generated by OrcaSlicer Core (Node.js addon) on 2025-09-06 at 22:10:00
; model printing time: estimated
; total layer number: 1
;_GP_TOTAL_LAYER_NUMBER_PLACEHOLDER
; model label id: 1000
; filament_density: 1.24
; filament_diameter: 1.75
; max_z_height: 0.2
; HEADER_BLOCK_END

; CONFIG_BLOCK_START
; accel_to_decel_enable = 1
; accel_to_decel_factor = 50%
; activate_air_filtration = 0,0,0,0,0
; activate_chamber_temp_control = 0,0,0,0,0
; adaptive_bed_mesh_margin = 0
; adaptive_pressure_advance = 0,0,0,0,0
; auxiliary_fan = 1
; bed_exclude_area = 0x0,18x0,18x28,0x28
; bed_mesh_max = 99999,99999
; bed_mesh_min = -99999,-99999
; bed_mesh_probe_distance = 50,50
; best_object_pos = 0.5,0.5
; bottom_shell_layers = 3
; bottom_shell_thickness = 0
; bottom_solid_infill_flow_ratio = 1
; bottom_surface_pattern = monotonic
; bridge_acceleration = 50%
; bridge_angle = 0
; bridge_density = 100%
; bridge_flow = 1
; bridge_no_support = 0
; bridge_speed = 50
; brim_object_gap = 0.1
; brim_type = no_brim
; brim_width = 5
; chamber_temperature = 0,0,0,0,0
; close_fan_the_first_x_layers = 1,1,1,1,1
; complete_print_exhaust_fan_speed = 70,70,70,70,70
; cool_plate_temp = 60,60,35,35,35
; cool_plate_temp_initial_layer = 60,60,35,35,35
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; counterbore_hole_bridging = none
; curr_bed_type = Cool Plate
; default_acceleration = 10000
; default_filament_colour = ;;;;;
; default_filament_profile = "Bambu PLA Basic @BBL X1C"
; default_jerk = 8
; default_print_profile = 0.20mm Standard @BBL X1C
; deretraction_speed = 30
; detect_narrow_internal_solid_infill = 1
; detect_overhang_wall = 1
; detect_thin_wall = 0
; different_settings_to_system = layer_height;sparse_infill_pattern;wall_generator;wall_loops;;;;;;
; dont_filter_internal_bridges = disabled
; dont_slow_down_outer_wall = 0,0,0,0,0
; draft_shield = disabled
; during_print_exhaust_fan_speed = 70,70,70,70,70
; elefant_foot_compensation = 0.15
; elefant_foot_compensation_layers = 1
; emit_machine_limits_to_gcode = 1
; enable_arc_fitting = 1
; enable_extra_bridge_layer = disabled
; enable_filament_ramming = 0
; enable_long_retraction_when_cut = 2
; enable_overhang_bridge_fan = 1,1,1,1,1
; enable_overhang_speed = 1
; enable_pressure_advance = 0,0,0,0,0
; enable_prime_tower = 0
; enable_support = 0
; enforce_support_layers = 0
; eng_plate_temp = 0,0,0,0,0
; eng_plate_temp_initial_layer = 0,0,0,0,0
; ensure_vertical_shell_thickness = ensure_all
; exclude_object = 0
; extra_loading_move = -2
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height_to_lid = 90
; extruder_clearance_height_to_rod = 34
; extruder_clearance_radius = 57
; extruder_colour = #DE4343;#D1D3D5;#757575;#0078BF;#000000
; extruder_offset = 0x2
; fan_cooling_layer_time = 100,100,100,100,100
; fan_kickstart = 0
; fan_max_speed = 100,100,100,100,100
; fan_min_speed = 100,100,100,100,100
; filament_colour = #DE4343;#D1D3D5;#757575;#0078BF;#000000
; filament_cooling_final_speed = 3.4,3.4,3.4,3.4,3.4
; filament_cooling_initial_speed = 2.2,2.2,2.2,2.2,2.2
; filament_cooling_moves = 4,4,4,4,4
; filament_cost = 24.99,24.99,24.99,24.99,24.99
; filament_density = 1.32,1.26,1.32,1.32,1.32
; filament_diameter = 1.75,1.75,1.75,1.75,1.75
; filament_flow_ratio = 0.98,0.98,0.98,0.98,0.98
; filament_ids = GFA01;GFA00;GFA01;GFA01;GFA01
; filament_is_support = 0,0,0,0,0
; filament_loading_speed = 28,28,28,28,28
; filament_loading_speed_start = 3,3,3,3,3
; filament_max_volumetric_speed = 22,21,22,22,22
; filament_settings_id = "Bambu PLA Matte @BBL X1C";"Bambu PLA Basic @BBL X1C";"Bambu PLA Matte @BBL X1C";"Bambu PLA Matte @BBL X1C";"Bambu PLA Matte @BBL X1C"
; filament_shrink = 100%,100%,100%,100%,100%
; filament_soluble = 0,0,0,0,0
; filament_type = PLA;PLA;PLA;PLA;PLA
; filament_unloading_speed = 90,90,90,90,90
; filament_unloading_speed_start = 100,100,100,100,100
; filament_vendor = "Bambu Lab";"Bambu Lab";"Bambu Lab";"Bambu Lab";"Bambu Lab"
; filename_format = {input_filename_base}_{filament_type[0]}_{print_time}.gcode
; filter_out_gap_fill = 0
; first_layer_print_sequence = 0
; flush_into_infill = 0
; flush_into_objects = 0
; flush_into_support = 1
; flush_multiplier = 1
; flush_volumes_matrix = 0,440,218,247,152,223,0,123,253,130,203,342,0,217,123,400,500,310,0,138,469,554,387,452,0
; flush_volumes_vector = 140,140,140,140,140,140,140,140,140,140
; full_fan_speed_layer = 0,0,0,0,0
; fuzzy_skin = none
; fuzzy_skin_first_layer = 0
; fuzzy_skin_noise_type = classic
; fuzzy_skin_octaves = 4
; fuzzy_skin_persistence = 0.5
; fuzzy_skin_point_distance = 0.3
; fuzzy_skin_scale = 1
; fuzzy_skin_thickness = 0.2
; gap_fill_target = nowhere
; gap_infill_speed = 250
; gcode_add_line_number = 0
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = 1
; has_scarf_joint_seam = 0
; head_wrap_detect_zone = 
; high_current_on_filament_swap = 0
; hole_to_polyhole = 0
; hole_to_polyhole_threshold = 0.01
; hole_to_polyhole_twisted = 1
; host_type = octoprint
; hot_plate_temp = 60,60,55,55,55
; hot_plate_temp_initial_layer = 60,60,55,55,55
; idle_temperature = 0,0,0,0,0
; independent_support_layer_height = 1
; infill_anchor = 400%
; infill_anchor_max = 20
; infill_combination = 0
; infill_direction = 45
; infill_jerk = 9
; infill_wall_overlap = 15%
; initial_layer_acceleration = 500
; initial_layer_infill_speed = 105
; initial_layer_jerk = 9
; initial_layer_line_width = 0.5
; initial_layer_min_bead_width = 85%
; initial_layer_print_height = 0.2
; initial_layer_speed = 50
; initial_layer_travel_speed = 100%
; inner_wall_acceleration = 10000
; inner_wall_jerk = 9
; inner_wall_line_width = 0.45
; inner_wall_speed = 300
; interface_shells = 0
; interlocking_beam = 0
; interlocking_beam_layer_count = 2
; interlocking_beam_width = 0.8
; interlocking_boundary_avoidance = 2
; interlocking_depth = 2
; interlocking_orientation = 22.5
; internal_bridge_angle = 0
; internal_bridge_density = 100%
; internal_bridge_fan_speed = -1,-1,-1,-1,-1
; internal_bridge_flow = 1
; internal_bridge_speed = 150%
; internal_solid_infill_acceleration = 100%
; internal_solid_infill_line_width = 0.42
; internal_solid_infill_pattern = monotonic
; internal_solid_infill_speed = 250
; ironing_angle = -1
; ironing_flow = 10%
; ironing_inset = 0.21
; ironing_pattern = zig-zag
; ironing_spacing = 0.15
; ironing_speed = 30
; ironing_type = no ironing
; is_infill_first = 0
; layer_change_gcode = ; layer num/total_layer_count: {layer_num+1}/[total_layer_count]\nM622.1 S1\nM1002 judge_flag timelapse_record_flag\nM622 J1\n{if timelapse_type == 0}\nM971 S11 C10 O0\n{elsif timelapse_type == 1}\nG92 E0\nG1 E-[retraction_length] F1800\nG17\nG2 Z{layer_z + 0.4} I0.86 J0.86 P1 F20000\nG1 X65 Y245 F20000\nG17\nG2 Z{layer_z} I0.86 J0.86 P1 F20000\nG1 Y265 F3000\nM400 P300\nM971 S11 C10 O0\nG92 E0\nG1 E[retraction_length] F300\nG1 X100 F5000\nG1 Y255 F20000\n{endif}\nM623\nM73 L{layer_num+1}\nM991 S0 P{layer_num}
; layer_height = 0.2
; line_width = 0.42
; long_retractions_when_cut = 0
; machine_end_gcode = ;===== date: 20240528 =====================\nM400\nG92 E0\nG1 E-0.8 F1800\nG1 Z{max_layer_z + 0.5} F900\nG1 X65 Y245 F12000\nG1 Y265 F3000\nG1 X65 Y245 F12000\nG1 Y265 F3000\nM140 S0\nM106 S0\nM106 P2 S0\nM106 P3 S0\nG1 X100 F12000\nM620 S255\nG1 X20 Y50 F12000\nG1 Y-3\nT255\nG1 X65 F12000\nG1 Y265\nG1 X100 F12000\nM621 S255\nM104 S0
; machine_load_filament_time = 29
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 20000,20000
; machine_max_acceleration_retracting = 5000,5000
; machine_max_acceleration_travel = 9000,9000
; machine_max_acceleration_x = 20000,20000
; machine_max_acceleration_y = 20000,20000
; machine_max_acceleration_z = 500,200
; machine_max_jerk_e = 2.5,2.5
; machine_max_jerk_x = 9,9
; machine_max_jerk_y = 9,9
; machine_max_jerk_z = 3,3
; machine_max_speed_e = 30,30
; machine_max_speed_x = 500,200
; machine_max_speed_y = 500,200
; machine_max_speed_z = 20,20
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; machine_pause_gcode = M400 U1
; machine_start_gcode = ;===== machine: X1 ====================\n;===== date: 20240919 ==================\nM17\nM400 S1\nM1006 S1\nM104 S75\nM290 X40 Y40 Z2.6666666\nG91\nM17 Z0.4\nG380 S2 Z30 F300\nG380 S2 Z-25 F300\nG1 Z5 F300\nG90\nM17 X1.2 Y1.2 Z0.75\nM960 S5 P1\nG90\nM220 S100\nM221 S100\nM73.2 R1.0\nM1002 set_gcode_claim_speed_level : 5\nM221 X0 Y0 Z0\nG29.1 Z{+0.0}\nM204 S10000
; machine_tool_change_time = 0
; machine_unload_filament_time = 28
; make_overhang_printable = 0
; make_overhang_printable_angle = 55
; make_overhang_printable_hole_size = 0
; manual_filament_change = 0
; max_bridge_length = 0
; max_layer_height = 0.28
; max_travel_detour_distance = 0
; min_bead_width = 85%
; min_feature_size = 25%
; min_layer_height = 0.08
; min_skirt_length = 0
; minimum_sparse_infill_area = 15
; notes = 
; nozzle_diameter = 0.4
; nozzle_height = 4.2
; nozzle_hrc = 0
; nozzle_temperature = 210,210,220,220,220
; nozzle_temperature_initial_layer = 210,210,220,220,220
; nozzle_temperature_range_high = 240,240,240,240,240
; nozzle_temperature_range_low = 190,190,190,190,190
; nozzle_type = hardened_steel
; nozzle_volume = 107
; only_one_wall_first_layer = 0
; only_one_wall_top = 1
; ooze_prevention = 0
; other_layers_print_sequence = 0
; outer_wall_acceleration = 5000
; outer_wall_jerk = 9
; outer_wall_line_width = 0.42
; outer_wall_speed = 200
; overhang_fan_speed = 100,100,100,100,100
; overhang_fan_threshold = 50%,50%,50%,50%,50%
; overhang_reverse = 0
; overhang_reverse_internal_only = 0
; overhang_reverse_threshold = 50%
; overhang_speed_classic = 0
; parking_pos_retraction = 92
; post_process = 
; precise_outer_wall = 0
; precise_z_height = 0
; preferred_orientation = 0
; pressure_advance = 0.02,0.02,0.02,0.02,0.02
; prime_tower_brim_width = 3
; prime_tower_width = 35
; prime_volume = 45
; print_compatible_printers = "Bambu Lab X1 Carbon 0.4 nozzle";"Bambu Lab X1 0.4 nozzle";"Bambu Lab P1S 0.4 nozzle";"Bambu Lab X1E 0.4 nozzle"
; print_flow_ratio = 1
; print_order = default
; print_sequence = by layer
; print_settings_id = 0.20mm Standard @BBL X1C
; printable_area = 0x0,256x0,256x256,0x256
; printable_height = 250
; printer_model = Bambu Lab X1 Carbon
; printer_notes = 
; printer_settings_id = Bambu Lab X1 Carbon 0.4 nozzle
; printer_structure = corexy
; printer_technology = FFF
; printer_variant = 0.4
; printhost_authorization_type = key
; printhost_ssl_ignore_revoke = 0
; printing_by_object_gcode = 
; purge_in_prime_tower = 0
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 2
; raft_layers = 0
; reduce_crossing_wall = 0
; reduce_fan_stop_start_freq = 1,1,1,1,1
; reduce_infill_retraction = 1
; required_nozzle_HRC = 3,3,3,3,3
; resolution = 0.012
; retract_before_wipe = 0%
; retract_length_toolchange = 2
; retract_lift_above = 0
; retract_lift_below = 249
; retract_lift_enforce = All Surfaces
; retract_on_top_layer = 1
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_when_changing_layer = 1
; retraction_distances_when_cut = 18
; retraction_length = 0.8
; retraction_minimum_travel = 1
; retraction_speed = 30
; role_based_wipe_speed = 1
; rotate_solid_infill_direction = 1
; scan_first_layer = 1
; seam_gap = 10%
; seam_position = aligned
; silent_mode = 0
; single_extruder_multi_material = 1
; single_extruder_multi_material_priming = 0
; skirt_distance = 2
; skirt_height = 1
; skirt_loops = 0
; skirt_speed = 50
; slice_closing_radius = 0.049
; slicing_mode = regular
; slow_down_for_layer_cooling = 1,1,1,1,1
; slow_down_layer_time = 4,4,4,4,4
; slow_down_layers = 0
; slow_down_min_speed = 20,20,20,20,20
; slowdown_for_curled_perimeters = 1
; small_perimeter_speed = 50%
; small_perimeter_threshold = 0
; solid_infill_direction = 45
; solid_infill_filament = 1
; sparse_infill_acceleration = 100%
; sparse_infill_density = 15%
; sparse_infill_filament = 1
; sparse_infill_line_width = 0.45
; sparse_infill_pattern = gyroid
; sparse_infill_speed = 270
; spiral_mode = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; support_air_filtration = 0
; support_angle = 0
; support_base_pattern = default
; support_base_pattern_spacing = 2.5
; support_bottom_interface_spacing = 0.5
; support_bottom_z_distance = 0.2
; support_critical_regions_only = 0
; support_expansion = 0
; support_filament = 0
; support_interface_bottom_layers = 2
; support_interface_filament = 0
; support_interface_loop_pattern = 0
; support_interface_not_for_body = 1
; support_interface_pattern = auto
; support_interface_spacing = 0.5
; support_interface_speed = 80
; support_interface_top_layers = 2
; support_line_width = 0.42
; support_material_interface_fan_speed = -1,-1,-1,-1,-1
; support_object_first_layer_gap = 0.2
; support_object_xy_distance = 0.35
; support_on_build_plate_only = 0
; support_remove_small_overhang = 1
; support_speed = 150
; support_style = default
; support_threshold_angle = 30
; support_top_z_distance = 0.2
; support_type = normal(auto)
; temperature_vitrification = 45,45,45,45,45
; template_custom_gcode = 
; thick_bridges = 0
; thick_internal_bridges = 1
; thumbnails = 48x48/PNG,300x300/PNG
; thumbnails_format = PNG
; time_cost = 0
; time_lapse_gcode = 
; timelapse_type = 0
; top_shell_layers = 5
; top_shell_thickness = 1
; top_solid_infill_flow_ratio = 1
; top_surface_acceleration = 2000
; top_surface_jerk = 9
; top_surface_line_width = 0.42
; top_surface_pattern = monotonicline
; top_surface_speed = 200
; travel_acceleration = 10000
; travel_jerk = 12
; travel_speed = 500
; travel_speed_z = 0
; upward_compatible_machine = "Bambu Lab P1S 0.4 nozzle";"Bambu Lab P1P 0.4 nozzle";"Bambu Lab X1 0.4 nozzle";"Bambu Lab X1E 0.4 nozzle";"Bambu Lab A1 0.4 nozzle"
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; wall_direction = auto
; wall_distribution_count = 1
; wall_filament = 1
; wall_generator = arachne
; wall_loops = 4
; wall_sequence = inner wall/outer wall
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_distance = 1
; wipe_speed = 80%
; wipe_tower_bridging = 10
; wipe_tower_cone_angle = 0
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_spacing = 100%
; wipe_tower_filament = 0
; wipe_tower_max_purge_speed = 90
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_x = 165.000
; wipe_tower_x = 165,165,165,165,165,165,165
; wipe_tower_y = 211.626
; wipe_tower_y = 211.626,211.626,211.626,211.626,211.626,211.626,211.626
; wiping_volumes_extruders = 70,70,70,70,70,70,70,70,70,70
; xy_contour_compensation = 0
; xy_hole_compensation = 0
; z_hop = 0.4
; z_hop_types = Auto Lift
; z_offset = 0
; first_layer_bed_temperature = 60
; first_layer_temperature = 210
; CONFIG_BLOCK_END

;===== machine setup =================
G90 ; absolute positioning
G21 ; set units to millimeters
M82 ; use absolute distances for extrusion
G92 E0 ; reset extruder

;===== temperature setup =============
M140 S60 ; set bed temp
M190 S60 ; wait for bed temp
M104 S210 ; set nozzle temp
M109 S210 ; wait for nozzle temp

;===== motion setup ==================
M204 S10000 ; set acceleration
M205 X8 Y8

;===== start printing =================
; CHANGE_LAYER
; Z_HEIGHT: 0.2
; LAYER_HEIGHT: 0.2
; layer num/total_layer_count: 1/1

; printing object TestObject id:0 copy 0
G1 X100 Y100 F6000 ; move to start position
G1 Z0.2 F1200 ; move to first layer height
G1 E2 F1800 ; prime extruder

; FEATURE: Outer wall
G1 F1800
G1 X110 Y100 E0.5 ; print line
G1 X110 Y110 E0.5 ; print line
G1 X100 Y110 E0.5 ; print line
G1 X100 Y100 E0.5 ; print line

; FEATURE: Inner wall
G1 X102 Y102 F6000 ; move to inner wall
G1 F1800
G1 X108 Y102 E0.3 ; print inner line
G1 X108 Y108 E0.3 ; print inner line
G1 X102 Y108 E0.3 ; print inner line
G1 X102 Y102 E0.3 ; print inner line

; FEATURE: Sparse infill
G1 X104 Y104 F6000 ; move to infill
G1 F1800
G1 X106 Y106 E0.2 ; infill line

;===== ending sequence ================
G1 E-2 F1800 ; retract
G1 Z5 F1200 ; lift nozzle
G1 X0 Y200 F6000 ; move to back
M104 S0 ; turn off nozzle
M140 S0 ; turn off bed
M106 S0 ; turn off fan
M84 ; disable motors
