name: DOCKER CI

on:
  push:
    branches: [ "main" ]

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build-docker:
    strategy:
      matrix:
        arch: [amd64, arm64]
        include:
          - arch: amd64
            platform: linux/amd64
            runner: ubuntu-latest
          - arch: arm64
            platform: linux/arm64
            runner: ubuntu-22.04-arm64


    name: Build addon base and slicer-api images
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 180
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Login to GHCR (optional; enables pulling/pushing if needed)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Derive Orca version/arch
        id: meta
        run: |
          bash scripts/ci/derive_meta.sh
        shell: bash

      - name: Compute image tags from source (owner/version/arch)
        run: |
          lower_owner=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "DEPS_TAG=ghcr.io/${lower_owner}/orcaslicer-build-deps:${{ steps.meta.outputs.version }}a-${{ matrix.arch }}" >> "$GITHUB_ENV"
          echo "CORE_TAG=ghcr.io/${lower_owner}/orcaslicer-core:${{ steps.meta.outputs.version }}a-${{ matrix.arch }}" >> "$GITHUB_ENV"
          echo "ADDON_BASE_TAG=ghcr.io/${lower_owner}/orca-addon-base:${{ steps.meta.outputs.version }}a-${{ matrix.arch }}" >> "$GITHUB_ENV"
          echo "SLICER_TAG=ghcr.io/${lower_owner}/slicer-api:${{ steps.meta.outputs.version }}a-${{ matrix.arch }}" >> "$GITHUB_ENV"
        shell: bash

      - name: Build DEPS image (target=deps)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          target: deps
          platforms: ${{ matrix.platform }}
          build-args: |
            ENFORCE_PREBUILT_BASE=false
          push: true
          tags: |
            ${{ env.DEPS_TAG }}

      - name: Build CORE image (target=core, reusing deps)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          target: core
          platforms: ${{ matrix.platform }}
          build-args: |
            ENFORCE_PREBUILT_BASE=false
            BASE_DEPS_IMAGE=${{ env.DEPS_TAG }}
            USE_PREBUILT_DEPS=true
          push: true
          tags: |
            ${{ env.CORE_TAG }}

      - name: Build ADDON base image (target=base)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          target: base
          platforms: ${{ matrix.platform }}
          build-args: |
            ENFORCE_PREBUILT_BASE=true
            USE_PREBUILT_DEPS=true
            BASE_DEPS_IMAGE=${{ env.DEPS_TAG }}
            BASE_CORE_IMAGE=${{ env.CORE_TAG }}
          push: true
          tags: |
            ${{ env.ADDON_BASE_TAG }}

      - name: Build slicer-api image (consumes addon base)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: node-api/Dockerfile
          platforms: ${{ matrix.platform }}
          build-args: |
            ADDON_BASE=${{ env.ADDON_BASE_TAG }}
          push: true
          tags: |
            ${{ env.SLICER_TAG }}

