name: Build and Push orcaslicer-build-deps (GHCR, linux/amd64)

on:
  # Build only when manually triggered to avoid unnecessary runs
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

concurrency:
  group: ghcr-orcaslicer-build-deps-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-push:
    runs-on: ubuntu-latest  # native amd64 runner, no emulation
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          # Use rootless buildkit (fast and safe). Runner is amd64, so no QEMU/emulation.
          driver-opts: image=moby/buildkit:rootless

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (stage 'orcaslicer' → ghcr)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          target: orcaslicer
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/orcaslicer-build-deps:3.0.1a
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false

