name: Build and Push orcaslicer-build-deps (GHCR, linux/amd64)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag to push (e.g., 3.0.1a)'
        required: true
        default: '3.0.1a'
      ci_max_jobs:
        description: 'CI_MAX_JOBS passed to the build'
        required: false
        default: '2'

permissions:
  contents: read
  packages: write

concurrency:
  group: ghcr-orcaslicer-build-deps-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-push:
    runs-on: ubuntu-latest  # native amd64 runner, no emulation
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          # Use rootless buildkit (fast and safe). Runner is amd64, so no QEMU/emulation.
          driver-opts: image=moby/buildkit:rootless

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (stage 'deps' → ghcr)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          target: deps
          platforms: linux/amd64
          pull: true
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/orcaslicer-build-deps:${{ inputs.tag }}-amd64
          cache-from: type=gha,scope=orcaslicer-amd64
          cache-to: type=gha,mode=max,scope=orcaslicer-amd64
          build-args: |
            CI_MAX_JOBS=${{ inputs.ci_max_jobs }}
          provenance: false

